# Build FastCarz Web, API and Test 

name: '$(Date:yyyyMMdd)$(Rev:.r)'

# Trigger build when branches are updated
trigger:
  branches:
    include:
      - 'master'
pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'

# Agent jobs
stages:
  - stage: 'Build'
    jobs:
     - job: Build API
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build WebAPI
        inputs:
        command: build
        projects: '**/WebAPI.csproj'
        arguments: '--configuration Release'
     
     - job: Build Web App frontend
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build Web Application
        inputs:
        command: build
        projects: '**/WebApplication.csproj'
        arguments: '--configuration Release'

  - stage: 'Test'
    jobs:
     - job: Run Tests
      steps:
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
        command: test
        projects: '**/FastCarzTests.csproj'
        arguments: '--configuration $(buildConfiguration)'
      
